config/routes.rb
Rails.application.routes.draw do


  get 'home' => 'static_pages#home', as: :home
  get 'about' => 'static_pages#about', as: :about

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :resourceries, only: [:new, :create, :destroy]
  resources :invitations, only: [:show]
  resources :users do
    resources :resources
    resources :philosophies, only: [:new, :create, :update, :edit]
    resources :certifications, only: [:new, :create, :update, :edit, :destroy]
  end
  resources :preps do
    resources :contests
    resources :photos
    resources :cardios
    resources :target_cardios
    resources :macros
    resources :target_macros
    resources :bodyweights
    resources :resources, only: [:show]
    resources :resourceries, only: [:index]
    resources :conversations, only: [:create] do
      resources :messages, only: [:new, :create, :index]
    end
  end


  root 'users#show'
  get 'preps/:prep_id/photos/poses/:tag' => 'photos#index', as: :pose
  get 'preps/:prep_id/self_coach' => 'preps#self_coach', as: :selfie
  get 'preps/:prep_id/coaches' => 'users#index', as: :coaches
  get 'preps/:prep_id/coach/:id' => 'users#show', as: :coach
  get 'preps/:prep_id/coach_request/:id' => 'invitations#new', as: :new_coach_request
  post 'preps/:prep_id/coach_request/:id' => 'invitations#create', as: :coach_request
  get 'preps/:prep_id/invite/:id' => 'invitations#show', as: :invite_view
  post 'preps/:prep_id/invite/:id' => 'invitations#accept_invite', as: :accept_invite
  delete 'preps/:prep_id/invite/:id' => 'invitations#destroy', as: :deny_invite
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @no_nav = true
  end

  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<div class="row">
  <div class="small-12 columns about">
    <h2 class="green">About Musclewizards</h2>
    <p>
      A lot of work goes into looking your best for a contest, and MuscleWizards provides a simple place to store and track all your relevant data.  It is geared towards an IIFYM-based approach to contest dieting.
    </p>
    <h4 class="green">Key Features:</h4>
    <ul class="no-bullet">
      <li><strong>Find a coach</strong> easily to assist you with your prep. They are available through in-app messaging, and will provide you with your goals and feedback on your progress.</li>
      <li><strong>Easy data entry</strong> for daily macros, weigh-ins and cardio logging.</li>
      <li><strong>Simple Progress Photo Comparisons</strong>. For physique competitions, photos are key for tracking progress towards your goals.  Our interface provides easy uploading, and photos can be tagged by pose for simple chronological comparisons.</li>
      <li><strong>Historical data tracking</strong>.  All data points are tracked in real time as they are entered and are easy to visualize with graphs and tables.</li>
    </ul>
    <div class="button-group">
      <%= link_to "Sign Up Now", new_user_registration_path, class: "button", id: "sign-up" %>
      <%= link_to "Back to Home", home_path, class: "button", id: "home" %>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="row">
  <div class="text-center title">
    <h1><span class="green">Muscle</span>Wizards</h1>
    <h3>Contest Prep. Simplified.</h3>
    <%= link_to "Find out more", about_path %>
  </div>
  <div class="medium-6 columns text-center sign-in coach">
    <h5>I'm a</h5>
    <h1>COACH</h1>
    <%= link_to "SIGN IN", new_user_session_path, class: "button" %>
    <h6>OR</h6>
    <%= link_to "SIGN UP", new_user_registration_path(coach: true), class: "button" %>
  </div>
  <div class="medium-6 columns text-center sign-in athlete">
    <h5>I'm an</h5>
    <h1>ATHLETE</h1>
    <%= link_to "SIGN IN", new_user_session_path, class: "button" %>
    <h6>OR</h6>
    <%= link_to "SIGN UP", new_user_registration_path, class: "button" %>
  </div>
</div>

app/views/static_pages/main.html.erb
<div class="row">
  <div class="text-center">
    <h1>MuscleWizards</h1>
    <h3>Contest Prep. Simplified.</h3>
  </div>
  <div class="medium-6 columns text-center">
    <h5>I'm a</h5>
    <h2>COACH</h2>
    <%= link_to "SIGN IN", "#", class: "button" %>
    <h5>OR</h5>
    <%= link_to "SIGN UP", "#", class: "button" %>
  </div>
  <div class="medium-6 columns text-center">
    <h5>I'm an</h5>
    <h2>ATHLETE</h2>
    <%= link_to "SIGN IN", new_user_session_path, class: "button" %>
    <h5>OR</h5>
    <%= link_to "SIGN UP", new_user_registration_path, class: "button" %>
  </div>
</div>