config/routes.rb
Rails.application.routes.draw do


  get 'home' => 'static_pages#home', as: :home
  get 'about' => 'static_pages#about', as: :about

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :resourceries, only: [:new, :create, :destroy]
  resources :invitations, only: [:show]
  resources :users do
    resources :resources
    resources :philosophies, only: [:new, :create, :update, :edit]
    resources :certifications, only: [:new, :create, :update, :edit, :destroy]
  end
  resources :preps do
    resources :contests
    resources :photos
    resources :cardios
    resources :target_cardios
    resources :macros
    resources :target_macros
    resources :bodyweights
    resources :resources, only: [:show]
    resources :resourceries, only: [:index]
    resources :conversations, only: [:create] do
      resources :messages, only: [:new, :create, :index]
    end
  end


  root 'users#show'
  get 'preps/:prep_id/photos/poses/:tag' => 'photos#index', as: :pose
  get 'preps/:prep_id/self_coach' => 'preps#self_coach', as: :selfie
  get 'preps/:prep_id/coaches' => 'users#index', as: :coaches
  get 'preps/:prep_id/coach/:id' => 'users#show', as: :coach
  get 'preps/:prep_id/coach_request/:id' => 'invitations#new', as: :new_coach_request
  post 'preps/:prep_id/coach_request/:id' => 'invitations#create', as: :coach_request
  get 'preps/:prep_id/invite/:id' => 'invitations#show', as: :invite_view
  post 'preps/:prep_id/invite/:id' => 'invitations#accept_invite', as: :accept_invite
  delete 'preps/:prep_id/invite/:id' => 'invitations#destroy', as: :deny_invite
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :prep
  belongs_to :user
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_prep
  before_action :user_owns_prep, only: [:new, :create]

  def new
    @invitation = Invitation.new
    @coach = User.find(params[:id])
  end

  def create
    @invitation = Invitation.new(invitation_params)
    @coach = User.find(params[:id])
    @invitation.user = @coach
    @invitation.prep = @prep
    if @invitation.save
      flash[:success] = "Invitation sent!"
      InvitationMailer.invite(@coach, @prep).deliver_later
      redirect_to @prep
    else
      render :new
    end
  end

  def show
    @invitation = @prep.invitation
    @user = @prep.athlete
    @coach = User.find(params[:id])
  end

  def destroy
    @invitation = Invitation.find_by(user_id: params[:id])
    @coach = User.find(@invitation.user_id)
    @invitation.destroy
    InvitationMailer.reject(@coach, @prep).deliver_later
    redirect_to @prep
  end

  def accept_invite
    @invitation = @prep.invitation
    @coach = User.find(params[:id])
    @prep.coach_id = @coach.id
    @prep.save
    InvitationMailer.accept(@prep.athlete, @prep).deliver_later
    @invitation.destroy
    redirect_to @prep
  end

  private

  def invitation_params
    params.require(:invitation).permit(:message)
  end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/new.html.erb
<div class="row">
  <div class="medium-8 medium-centered column">
    <h2>Invite <%= @coach.name %> to coach this Prep</h2>
    <%= image_tag(@coach.avatar(:medium)) %>
    <%= simple_form_for @invitation, :url => coach_request_path(@prep, @coach) do |f| %>
      <%= f.input :message, placeholder: "Send your coach a message about this request (optional)" %>
      <%= f.button :submit %>
    <% end %>
    <%= link_to "Back to Coach", coach_path(@prep, @coach) %>
  </div>
</div>

app/views/invitations/show.html.erb
<div class="row">
  <div class="medium-4 columns">
    <%= render partial: 'users/user_info' %>
  </div>
  <div class="medium-8 columns">
    <h4><%= @user.name %> would like you to coach the Prep "<%= @prep.title %>"</h4>
    <% if @invitation.message %>
      <h4 class="green">Message from Athlete:</h4>
      <%= simple_format @invitation.message %>
    <% end %>
    <%= link_to "Accept Invitation", accept_invite_path(@prep, @coach), class: "button", method: :post %>
    <%= link_to "Decline", deny_invite_path(@prep, @coach), method: :delete, class: "button" %>
  </div>
</div>