config/routes.rb
Rails.application.routes.draw do


  get 'home' => 'static_pages#home', as: :home
  get 'about' => 'static_pages#about', as: :about

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :resourceries, only: [:new, :create, :destroy]
  resources :invitations, only: [:show]
  resources :users do
    resources :resources
    resources :philosophies, only: [:new, :create, :update, :edit]
    resources :certifications, only: [:new, :create, :update, :edit, :destroy]
  end
  resources :preps do
    resources :contests
    resources :photos
    resources :cardios
    resources :target_cardios
    resources :macros
    resources :target_macros
    resources :bodyweights
    resources :resources, only: [:show]
    resources :resourceries, only: [:index]
    resources :conversations, only: [:create] do
      resources :messages, only: [:new, :create, :index]
    end
  end


  root 'users#show'
  get 'preps/:prep_id/photos/poses/:tag' => 'photos#index', as: :pose
  get 'preps/:prep_id/self_coach' => 'preps#self_coach', as: :selfie
  get 'preps/:prep_id/coaches' => 'users#index', as: :coaches
  get 'preps/:prep_id/coach/:id' => 'users#show', as: :coach
  get 'preps/:prep_id/coach_request/:id' => 'invitations#new', as: :new_coach_request
  post 'preps/:prep_id/coach_request/:id' => 'invitations#create', as: :coach_request
  get 'preps/:prep_id/invite/:id' => 'invitations#show', as: :invite_view
  post 'preps/:prep_id/invite/:id' => 'invitations#accept_invite', as: :accept_invite
  delete 'preps/:prep_id/invite/:id' => 'invitations#destroy', as: :deny_invite
end

app/models/certification.rb
class Certification < ApplicationRecord
  belongs_to :user
  validates :name, :date_granted, presence: true
  validate :is_in_the_future

  def is_in_the_future
    if self.date_granted && self.date_granted > Time.now
      errors.add(:date_granted, "can't be a future date")
    end
  end
end

app/controllers/certifications_controller.rb
class CertificationsController < ApplicationController
  before_action :require_user

  def new
    @certification = Certification.new
  end

  def create
    @certification = current_user.certifications.new(certification_params)
    if @certification.save
      flash[:success] = "New certification saved!"
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def edit
    @certification = Certification.find(params[:id])
  end

  def update
    @certification = Certification.find(params[:id])
    if @certification.user == current_user && @certification.update_attributes(certification_params)
      flash[:success] = "Certification successfully updated!"
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def destroy
    @certification = Certification.find(params[:id])
    @certification.destroy if @certification.user == current_user
    redirect_to user_path(current_user)
  end

  private

  def certification_params
    params.require(:certification).permit(:name, :date_granted)
  end

end

app/helpers/certifications_helper.rb
module CertificationsHelper
end

app/views/certifications/_certification.html.erb
  <% certs.each do |cert| %>
    <ul class="no-bullet certification">
      <li><%= cert.name %><li>
      <li>Certified On: <%= cert.date_granted.strftime('%D') %></li>
    </ul>
    <%= link_to "Edit", edit_user_certification_path(current_user, cert), class: "underline" if @user == current_user %>
    <%= link_to "Delete", user_certification_path(user_id: current_user.id, id: cert), method: :delete, class: "underline" if @user == current_user %>
  <% end %>

app/views/certifications/_form.html.erb
<%= simple_form_for [current_user, @certification] do |f| %>
  <%= f.input :name %>
  <%= f.label "Date" %>
  <%= f.text_field :date_granted, placeholder: "eg. 2016-05-22" %>
  <div class="errors">
    <% if @certification.errors.messages[:date_granted] %>
      <small class="error"><%= @certification.errors.messages[:date_granted][0] %></small>
    <% end %>
  </div>
  <%= f.button :submit %>
<% end %>

app/views/certifications/edit.html.erb
<div class="row">
  <div class="medium-8 medium-centered column">
    <h2>Edit Certification</h2>
    <%= render partial: 'form' %>
    <%= link_to "Back to User Page", user_path(current_user) %>
  </div>
</div>

app/views/certifications/new.html.erb
<div class="row">
  <div class="medium-8 medium-centered column">
    <h2>New Certification</h2>
    <%= render partial: 'form' %>
    <%= link_to "Back to User Page", user_path(current_user) %>
  </div>
</div>