config/routes.rb
Rails.application.routes.draw do


  get 'home' => 'static_pages#home', as: :home
  get 'about' => 'static_pages#about', as: :about

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :resourceries, only: [:new, :create, :destroy]
  resources :invitations, only: [:show]
  resources :users do
    resources :resources
    resources :philosophies, only: [:new, :create, :update, :edit]
    resources :certifications, only: [:new, :create, :update, :edit, :destroy]
  end
  resources :preps do
    resources :contests
    resources :photos
    resources :cardios
    resources :target_cardios
    resources :macros
    resources :target_macros
    resources :bodyweights
    resources :resources, only: [:show]
    resources :resourceries, only: [:index]
    resources :conversations, only: [:create] do
      resources :messages, only: [:new, :create, :index]
    end
  end


  root 'users#show'
  get 'preps/:prep_id/photos/poses/:tag' => 'photos#index', as: :pose
  get 'preps/:prep_id/self_coach' => 'preps#self_coach', as: :selfie
  get 'preps/:prep_id/coaches' => 'users#index', as: :coaches
  get 'preps/:prep_id/coach/:id' => 'users#show', as: :coach
  get 'preps/:prep_id/coach_request/:id' => 'invitations#new', as: :new_coach_request
  post 'preps/:prep_id/coach_request/:id' => 'invitations#create', as: :coach_request
  get 'preps/:prep_id/invite/:id' => 'invitations#show', as: :invite_view
  post 'preps/:prep_id/invite/:id' => 'invitations#accept_invite', as: :accept_invite
  delete 'preps/:prep_id/invite/:id' => 'invitations#destroy', as: :deny_invite
end

app/views/resources/_form.html.erb
    <%= simple_form_for [current_user, @resource] do |f| %>
      <%= f.input :title %>
      <%= f.input :url, placeholder: "Optional" %>
      <%= f.input :body, placeholder: "Optional" %>
      <%= f.input :upload, as: :file %>
      <%= f.button :submit %>
    <% end %>

app/views/resources/_resource.html.erb
<div class="row resource">
  <div class="small-6 columns">
    <ul class="no-bullet">
      <% if @prep %>
        <% if resource_shared?(resource) %>
          <li><%= link_to (resource.title + unread_flag(resource)).html_safe, prep_resource_path(@prep, resource) %></li>
          <li>Shared on: <%= resource_shared_date(resource) %></li>
        <% else %>
          <li><%= link_to resource.title, prep_resource_path(@prep, resource) %></li>
          <li>Created at: <%= resource.created_at.strftime("%D") %></li>
        <% end %>
      <% else %>
        <li><%= link_to resource.title, user_resource_path(user_id: resource.user.id, id: resource.id) %></li>
      <% end %>
      <% if resource.user == current_user && !@prep %>
        <li>Created at: <%= resource.created_at.strftime("%D") %></li>
        <li>
          <%= link_to "Edit", edit_user_resource_path(user_id: current_user.id, id: resource.id), class: "underline" %>
          <%= link_to "Delete", user_resource_path(user_id: current_user.id, id: resource.id), class: "underline", method: :delete %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="small-6 columns text-right">
    <% if resource.user == current_user %>
      <%= render partial: 'resources/sharing_options', locals: { resource: resource } %>
    <% end %>
  </div>
</div>

app/views/resources/_sharing_options.html.erb
<% if @prep %>
  <div class="share-link">
    <% if resource_shared_with_prep(resource) %>
      <%= link_to "Unshare Resource", resourcery_path(id: Resourcery.where(resource_id: resource.id, prep_id: @prep.id).first), method: :delete %>
    <% else %>
      <%= link_to "+ Share Resource", resourceries_path(prep_id: @prep.id, resource_id: resource.id), method: :post %>
    <% end %>
  </div>
<% else %>
  <%= link_to "Share Resource", new_resourcery_path(resource: resource), class: "button", id: "share-button" %>
<% end %>

app/views/resources/edit.html.erb
<div class="row">
  <div class="medium-8 medium-centered column">
    <h2>Edit Resource</h2>
    <%= render partial: 'form' %>
  </div>
</div>

app/views/resources/index.html.erb
<div class="row">
  <div class="small-12 columns">
    <h2>Resources</h2>
    <%= render @resources %>
    <%= link_to "+ Add a New Resource", new_user_resource_path(current_user) unless @prep %>
    <div>
      <% if @prep %>
        <%= link_to "Back to Prep", @prep, class: "button", id: "back-user-butt" %>
      <% else %>
        <%= link_to "Back to User Profile", user_path(current_user), class: "button", id: "back-user-butt" %>
      <% end %>
    </div>
  </div>
</div>

app/views/resources/new.html.erb
<div class="row">
  <div class="medium-8 medium-centered column">
    <h2>New Resource</h2>
    <%= render partial: 'form' %>
    <%= link_to "Back to Resources", user_resources_path(current_user) %>
  </div>
</div>

app/views/resources/show.html.erb
<div class="row">
  <div class="medium-8 medium-centered column">
    <h2><%= @resource.title %></h2>
    <ul class="no-bullet">
      <li><%= simple_format(@resource.body) %><li>
      <li><%= link_to "Link to Resource", @resource.url, target: "_blank" if @resource.url %></li>
      <li><%= link_to "Link to Attached File", @resource.upload.url, target: "_blank" if @resource.upload_file_name %></li>
    </ul>
    <div class="navigation-buttons">
      <% if @prep %>
        <%= link_to "Back to Resources", prep_resourceries_path(@prep), class: "button" %>
        <%= link_to "Back to Prep", @prep, class: "button" %>
      <% else %>
        <%= link_to "Back to Resources", user_resources_path(current_user), class: "button" %>
      <% end %>
    </div>
  </div>
</div>